# Generated by Django 4.0.1 on 2022-11-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_patient_id_patient_p_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='city_info',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='disease',
            name='price_info',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
