# Generated by Django 4.0.1 on 2022-11-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_disease_city_info_disease_price_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_info', models.CharField(default='', max_length=100)),
                ('price_info', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='disease',
            name='city_info',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='price_info',
        ),
    ]
